version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: wimf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wimf
    ports:
      - "3306:3306"
    volumes:
      - wimf_mysql_data:/var/lib/mysql
volumes:
  wimf_mysql_data:
